name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      #credentials
      #username
      #password
      env:
        API_URL: somr-url.com
      ports:
        - 80
      #volumes:
      #  - vol_name: /path/in/container
      #  - /path/to/container
      #  - /path/in/host:/path/in/container
      #options: --cpus 1
    steps:
      - name: Log Node & Os Versions
        run: |
          node -v 
          cat /etc/os-release

      - name: Log_env
        run: echo $API_URL
      - name: Create a file
        run: echo 'Some Text' > text.txt
      - name: Container in a Step
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: '/usr/local/bin/node'
          args: -p 2+3

      - name: Log node version
        uses: docker://node:18.16-alpine3.17
        with:
          args: -v
      - name: Show file contents
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: cat
          args: text.txt
      - uses: actions/checkout@v3
      - name: Run a bash script
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: ./script.sh
          args: "Some string"
      - name: Send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WGBHOOK: ${{secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: From Github Actions
          SLACK_MESSAGE: "Actor: ${{github.actor}}, Event:${{ github.event_name}}"
          SLACK_COLOR: "#723fc4"
