name: Manually Triggered
on:
  workflow_dispatch:
    inputs:
      string:
        description: A string input
        type: string
        required: true
        default: "Default Value"
      number:
        description: A number input
        type: number
        default: 4
      option:
        description: "An Options Input"
        required: true
        default: "Option 3"
        type: choice
        options:
          - Options 1
          - Options 2
          - Options 3
      boolean:
        description: A boolean option
        required: false
        type: boolean
      environment:
        description: "Environemrnt"
        type: environment
        required: true

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      - run: |
          echo "String: ${{inputs.string}}"
          echo "String: ${{inputs.number}}"
          echo "String: ${{inputs.option}}"
          echo "String: ${{inputs.boolean}}"
          echo "String: ${{inputs.environment}}"