name: Matrix
on: [push]

jobs:
  node-matrix:
    continue-on-error: false
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14,15,16]
        inlcude:
          - os: ubuntu-latest
            is-ubuntu: true
          - os: mac-os
            node-version: 15
          - experimental: false
          - os: ubuntu-latest
            node-verson: 16
            experimental: true
          - os: ubuntu-latest
            node-version: 17
        exclude:
          - os: ubuntu-version
            node-version: 14    
      fail-fast: false
      #max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - run: echo '${{ toJson(matrix)}}'
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v