name: Status Check Functions
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: sleep 20
      - name: Step 2
        id: step-2
        run: exit 1
      - name: Runs on Failure
        #if: failure()
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo 'Step 2 has failed'
      - name: Runs on Success
        if: success()
        run: echo 'Run on Success'
      - name: Alwasy Runs
        if: success() || failure()
        run: echo 'Always Runs'
      - name: Runs When Cancelled
        if: cancelled()
        run: echo 'Runs on Cancelled'

  job-2: 
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'Job 2'
    
