name: Calling Reusable workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Input description'
        type: string
        default: 'Mo'
        required: false
jobs:
  calling-a-reusable-wf:
    uses: mmohuiddin/workflows/.github/workflows/reusable.yaml@main
    with: 
      name: ${{inputs.name }}
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
  calling-a-reusable-wf-in-the-same-repo:
    uses: ./.github/workflows/reusable-workflow.yaml
  using-reusable-wf-output:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-wf-in-the-same-repo
    steps:
      - run: echo {{ needs.calling-a-reusable-wf-in-the-same-repo.outputs.date}}

