name: Working dirs and Shells
on: [push]
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory and List Files
        run: |
          pwd
          ls -a
          ehco $GITHUB_SHA
          ehco $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
  display-wd-info-windows:
    runs-on: windows-latest
    steps:
      - name: Display Working Directory and List Files
        run: |
          pwd
          ls -a
          ehco $GITHUB_SHA
          ehco $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE


